config/routes.rb
Rails.application.routes.draw do

  resources :wallpapers
  resources :tags, only: [:show]

  root 'home#index'
end

app/models/wallpaper.rb
class Wallpaper < ActiveRecord::Base
  acts_as_taggable

  validates :name, presence: true
  validates :image, presence: true

  mount_uploader :image, WallpaperUploader

  def as_json(options)
    o = super
    o[:tags] = self.tag_list.map {|t| t.to_s}
    o
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used.limit(10)

    dup_ids = []
    @wallpaper_sets = @tags.map do |tag|
      wallpapers = tag.taggings.where.not(taggable_id: dup_ids)
                    .order(created_at: :desc).limit(10).map(&:taggable)
      dup_ids.concat wallpapers.map(&:id)

      {
        name: tag.name,
        wallpapers: wallpapers
      }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = ActsAsTaggableOn::Tag.find_by_name params[:id]
    if @tag
      @wallpapers = @tag.taggings.map(&:taggable)
    end
  end
end

app/controllers/wallpapers_controller.rb
class WallpapersController < ApplicationController
  def index
    @wallpapers = Wallpaper.all
  end

  def show
    @wallpaper = Wallpaper.find(params[:id])
  end

  def new
    @wallpaper = Wallpaper.new
    @all_tags = Wallpaper.tags_on(:tags).map{|t| t.name}
  end

  def edit
    @wallpaper = Wallpaper.find(params[:id])
    @all_tags = Wallpaper.tags_on(:tags).map{|t| t.name}
  end

  def create
    @wallpaper = Wallpaper.new(wallpaper_params)
    if @wallpaper.save
      redirect_to @wallpaper
    else
      render 'new'
    end
  end

  def update
    @wallpaper = Wallpaper.find(params[:id])

    if @wallpaper.update(wallpaper_params)
      redirect_to @wallpaper
    else
      render 'edit'
    end
  end

  def destroy
    @wallpaper = Wallpaper.find(params[:id])
    @wallpaper.destroy
    redirect_to wallpapers_path
  end

  private
    def wallpaper_params
      params.require(:wallpaper).permit(:name, :image, :tag_list)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/wallpapers_helper.rb
module WallpapersHelper
end

app/views/home/index.html.erb
<h1>Popular Tags</h1>
<%= link_to 'All Wallpapers', controller: 'wallpapers' %>

<% @wallpaper_sets.each do |ws| %>
  <% if ws[:wallpapers].count > 0 %>
    <%= react_component 'WallpaperSet', ws %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WallTrade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrap">

<div class="header">
  <a href="/" class="brand">Wall Trade</a>
</div>

<div class="app">
  <%= yield %>
</div>

</div>
</body>
</html>

app/views/tags/show.html.erb
<h1>Tag: <%= params[:id] %></h1>
<%= react_component 'Wallpapers', { data: (@wallpapers or []) } %>
<div class="actions"><%= link_to "Top", wallpapers_path %></div>

app/views/wallpapers/edit.html.erb
<h1>Editing wallpaper</h1>

<%= react_component 'WallpaperForm', {
    data: @wallpaper,
    errors: @wallpaper.errors,
    all_tags: @all_tags,
    form: {
        mode: 'edit',
        token: form_authenticity_token.to_s
      }
    } %>

<div class="actions">
  <%= link_to 'Back', wallpaper_path(@wallpaper) %> |
  <%= link_to 'Top', wallpapers_path %>
</div>

app/views/wallpapers/index.html.erb
<h1>Wallpapers</h1>
<div class="actions"><%= link_to 'New Wallpaper', new_wallpaper_path %></div>
<%= react_component 'Wallpapers', { data: @wallpapers } %>

app/views/wallpapers/new.html.erb
<h1>Add Wallpaper</h1>

<%= react_component 'WallpaperForm', {
    data: @wallpaper,
    errors: @wallpaper.errors,
    all_tags: @all_tags,
    form: {
        mode: 'new',
        token: form_authenticity_token.to_s
      }
    } %>

<div class="actions">
  <%= link_to 'Top', wallpapers_path %>
</div>

app/views/wallpapers/show.html.erb
<%= react_component 'Wallpaper', { data: @wallpaper } %>

<div class="actions">
  <%= link_to 'Edit', edit_wallpaper_path(@wallpaper) %> |
  <%= link_to 'Top', wallpapers_path %>
</div>